package Algorithm.GUI.sortgui;

import Algorithm.GUI.GuiFather;
import Algorithm.Sort.InsertionSort;
import Algorithm.Sort.MergeSort;
import Algorithm.Sort.StudentData;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import static Algorithm.Sort.SortUtils.printStudentData;

public class SortGUI extends GuiFather {
    private JButton sortGUI_determine;
    private JTextField sortGUI_input;
    private JPanel jPanel;
    private JLabel sortGUILabel;
    private JTextArea sortOutput;
    private StudentData[] studentData;
    private String type = "";

    private void setSortGUILabel() {
        sortGUILabel.setText("" +
                "<html>請選擇排序方法：" +
                "<br> 1.Insertion Sort" +
                "<br> 2.Merge Sort</html>");
    }

    private void selectFunction(String selectString) {
        switch (selectString) {

            case "1":
                studentData = new StudentData[]{
                        new StudentData(97502, "DS", 79, "DM", 76, "LA", 63, type),
                        new StudentData(97501, "DS", 76, "DM", 79, "LA", 98, type),
                        new StudentData(97523, "DS", 49, "DM", 49, "LA", 78, type)};
                InsertionSort insertionSort = new InsertionSort();
                insertionSort.sort(studentData);
                printStudentData(studentData, sortOutput);
                sortOutput.append(insertionSort.getSortData() + "\n");
                break;

            case "2":
                studentData = new StudentData[]{
                        new StudentData(97502, "DS", 79, "DM", 76, "LA", 63, type),
                        new StudentData(97501, "DS", 76, "DM", 79, "LA", 98, type),
                        new StudentData(97523, "DS", 49, "DM", 49, "LA", 78, type)};
                MergeSort mergeSort = new MergeSort();
                mergeSort.sort(studentData);
                printStudentData(studentData, sortOutput);
                sortOutput.append(mergeSort.getSortData() + "\n");
                break;

            case "DS":
                type = "DS";
                setSortGUILabel();
                break;

            case "DM":
                type = "DM";
                setSortGUILabel();
                break;

            case "LA":
                type = "LA";
                setSortGUILabel();
                break;
        }
    }

    public SortGUI(String windowName) {
        super(windowName);
        setContentPane(jPanel);
        setVisible(true);
        sortOutput.setEditable(false);

        sortGUI_determine.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                selectFunction(sortGUI_input.getText());
            }
        });

        sortGUI_input.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                super.keyPressed(e);
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    selectFunction(sortGUI_input.getText());
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel = new JPanel();
        jPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        sortGUI_determine = new JButton();
        sortGUI_determine.setText("確定");
        jPanel.add(sortGUI_determine, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sortGUI_input = new JTextField();
        jPanel.add(sortGUI_input, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        sortGUILabel = new JLabel();
        sortGUILabel.setText("請輸入科目名稱");
        jPanel.add(sortGUILabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sortOutput = new JTextArea();
        jPanel.add(sortOutput, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel;
    }
}
