package networking_programming.thread.homework1.gui;

import networking_programming.thread.homework1.util.Message;
import networking_programming.thread.homework1.util.valueGetter;
import networking_programming.thread.homework1.util.valuePutter;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class DataGUI extends JFrame {
    private JPanel jPanel;
    private JTextArea dataOutput;

    private String windowName = "顯示執行結果";

    public DataGUI(String windowName) {
        this.windowName = windowName + " & 有故意放慢給GUI顯示 要沒有放慢版本請註解Message.java 52行";
        setTitle(this.windowName);
        setSize(800, 800);
        dataOutput.setDoubleBuffered(true);
        dataOutput.setLineWrap(true);
        setContentPane(jPanel);
        setVisible(true);
        closeEvent();

        Message message = new Message(dataOutput);
        Thread putter = new valuePutter(message);
        Thread getter = new valueGetter(message);
        putter.start();
        getter.start();
    }

    protected void closeEvent() {
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                System.out.println(windowName + " Frame Closed");
                DataGUI.this.dispose();
                System.exit(0);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel = new JPanel();
        jPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        dataOutput = new JTextArea();
        dataOutput.setEditable(true);
        dataOutput.setEnabled(true);
        jPanel.add(dataOutput, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("有故意放慢給GUI顯示 要沒有放慢版本請註解Message.java 52行");
        jPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel;
    }

}
